### ISSUE TITLE
Build warning on Clang with -Wdeprecated-redundant-constexpr-static-def

### ISSUE THREAD

**Issue by stephenberry** [fastfloat/fast_float#254] opened 2024-07-22 13:54 UTC
out-of-line definition of constexpr static data member is redundant in C++17 and is deprecated

Enabling `-Wdeprecated-redundant-constexpr-static-def` with warnings as errors causes fast_float to not build on Clang.

Fixing this should make the code cleaner as well.

**Comment by lemire** [comment] 2024-07-22 17:07
@stephenberry pull request invited!

**Comment by stephenberry** [comment] 2024-07-23 19:47
I think to support C++11 you would need macros around the old expressions. Do you want this?

**Comment by lemire** [comment] 2024-07-23 20:44
The library is C++11 and we do not want to change this.

Using macros is acceptable.

**Comment by dalle** [comment] 2024-11-23 09:00
I can't reproduce this issue anymore, any more details on versions used @stephenberry?

**Comment by stephenberry** [comment] 2024-11-23 14:14
This issue was reported for version `6.1.3`, perhaps someone fixed it. Are you making sure to build with C++17 or later?

**Comment by dalle** [comment] 2024-11-23 14:59
This was fixed in #268 for release 6.1.5.

**Comment by dalle** [comment] 2024-11-23 15:01
Thank you for your report, I'm closing this issue.

**Closed by dalle** 2024-11-23 15:01 UTC
