### ISSUE TITLE
`parse_infnan` should return an invalid argument error code when different from `inf` or `infinity`

### ISSUE THREAD

**Issue by captain-yoshi** [fastfloat/fast_float#164] opened 2022-12-28 05:01 UTC
A string that begins with `inf`, regardless of what comes after (except `""` and `"inity"`), will silently succeed :
```cpp
double d;
char str[] = "Informed"

if (parse_infnan(str, str + 8, &d)) {
    std::cout << "This should fail !" << std::endl;
    std::cout << d << std::endl;
}

// This should fail !
// inf
```

Some logic should be added [here](https://github.com/fastfloat/fast_float/blob/main/include/fast_float/parse_number.h#L49-L57) to handle this case.

**Comment by lemire** [comment] 2022-12-28 16:29
Yes. That is by design. Functions like `from_chars` do not do 'whole string' matching. Instead, they match the initial characters to a pattern. They also return a pointer to  where the pattern stop so that you can check whether the result is what you expected.

We follow the `from_chars` specification from the standard which defines the function as follows...

> Analyzes the character sequence [first,last) for a pattern described below. If no characters match the pattern or if the value obtained by parsing the matched characters is not representable in the type of value, value is unmodified, otherwise the characters matching the pattern are interpreted as a text representation of an arithmetic value, which is stored in value.

The pattern here is `Inf`. But we would equally patch `3.1242142informed` as  `3.1242142`. We are agnostic as to the trailing component. We just match an initial pattern and provide you with a pointer to the remainder. From this pointer, you (the user) can inspect the trailing component and see if there is an error. We cannot know whether `3.1242142informed` is valid or not, all we know is that it starts with a pattern we can match... it is up to you to check from the trailing component (`ormed`) and determine if it is acceptable to you.

 The `from_chars` functions are meant to be C++ versions of strto* family of C functions. The C functions were defined as "converting the initial portion of the string pointed to by nptr to double, float, and long double representation, respectively."

And indeed, that's what they do... the following code shows that the first three characters are parsed and the 'infinity' value is found...

```C++
#include <iostream>
#include <stdlib.h>

int main() {
  const char *x = "Informed";
  char *end = NULL;
  double y = strtod(x, &end);
  std::cout << y << " " << (end - x) << std::endl;
}
```

The `fast_float::from_chars` functions work similarly as you can verify...

```C++
#include "fast_float.h"
#include <iostream>
int main() {

  double d;
  char str[] = "Informed";

  auto answer = fast_float::from_chars(str, str + 8, d);
  if (answer.ec != std::errc()) {
    std::cerr << "parsing failure\n";
    return EXIT_FAILURE;
  }
  std::cout << "parsed the number " << d << std::endl;
  std::cout << answer.ptr - str << std::endl;
}
```

Admittedly, there are differences in how these functions are defined, for example, `from_chars` does not discard white space.



As a user of the library, if you are concerned by what gets matched, you should look at where `ptr` is left at. For example, if you expected it to match the whole string (`Informed`), then you should check that `answer.ptr - str==8`.

I am going to close this issue. If you disagree, please provide an explanation in terms of the C++ standard.

**Closed by lemire** 2022-12-28 16:29 UTC

**Comment by captain-yoshi** [comment] 2022-12-28 19:55
Tank you for the exhaustive answer ! It makes sense.
